title: Emma Templeton
logo: logo.png
show_downloads: true
google_analytics: G-CK7WDDRDK3
theme: jekyll-theme-minimal
CV: Templeton_CV.pdf
twitter: https://twitter.com/emma__templeton
scholar: https://scholar.google.com/citations?user=vdLzgoMAAAAJ&hl=en&oi=ao
